#!/bin/sh

#/**************************************************************************/
#/*                                                                        */
#/* Copyright (c) 2001, 2011 NoMachine, http://www.nomachine.com/.         */
#/*                                                                        */
#/* NXSCRIPTS, NX protocol compression and NX extensions to this software  */
#/* are copyright of NoMachine. Redistribution and use of the present      */
#/* software is allowed according to terms specified in the file LICENSE   */
#/* which comes in the source distribution.                                */
#/*                                                                        */
#/* Check http://www.nomachine.com/licensing.html for applicability.       */
#/*                                                                        */
#/* NX and NoMachine are trademarks of Medialogic S.p.A.                   */
#/*                                                                        */
#/* All rights reserved.                                                   */
#/*                                                                        */
#/**************************************************************************/


set -x

cd ${HOME}/NX

NX_PORT=11
export NX_PORT

NX_ROOT=${HOME}/.nx
#NX_ROOT=/var/NX
export NX_PORT

# Create directory for agent log.

rm -rf ${NX_ROOT}/C${NX_PORT} || exit
mkdir -p ${NX_ROOT}/C${NX_PORT} || exit

ln -s ~/.nx/control ${NX_ROOT}/C${NX_PORT}/control

#NX_HOST=nx/nx,accept=127.0.0.1,link=local,cache=2048k,data=0,stream=0,cookie=0b236d3a25631b1a0b2e213c6c076042,root=${NX_ROOT},log=errors,stat=stats
NX_HOST=nx/nx,link=local,cache=4096k,root=${NX_ROOT},log=errors,stat=stats
export NX_HOST

NX_DISPLAY=${NX_HOST}:${NX_PORT}
export NX_DISPLAY

NX_AGENT=:${NX_PORT}
export NX_AGENT

LD_LIBRARY_PATH="${HOME}/NX/nxcomp:${HOME}/NX/nxcompext:${HOME}/NX/nx-X11/exports/lib"
export LD_LIBRARY_PATH

# Color reduction for 16 and 32 bits display.

# 1 bit, 8 colors.
# NX_IMAGEMASK=128,63,240,7

# 2 bits, 64 colors.
# NX_IMAGEMASK=192,7,240,7

# 3 bits, 512 colors.
# NX_IMAGEMASK=224,5,240,4

# 4 bits, 4096 colors.
# NX_IMAGEMASK=240,4,240,2

# 5 bits, 32768 colors.
# NX_IMAGEMASK=248,3,248,2

# 6 bits, 262144 colors.
# NX_IMAGEMASK=252,2,252,1

# For all supported colors uncomment this.
# NX_IMAGEMASK=255,0,255,0

#export NX_IMAGEMASK

#NX_IMAGESPLIT=48,48,96,96
#NX_IMAGESPLIT=40,40,80,80
#NX_IMAGESPLIT=80,80,80,80
#NX_IMAGESPLIT=16384,16384,16384,16384
#export NX_IMAGESPLIT

#NX_IMAGEFRAME=1
#export NX_IMAGEFRAME

# -imgstop int           wait for confirm from nxproxy after any PutImage bigger than int
# -getifocus             mask GetInputFocus requests but wait for confirm from nxproxy
# -imgframe              let NXlib to draw a tiny rectangle around images
# -imgsplit PW,PH,BW,BH  force NXlib to split pixmaps and bitmaps to given width x height
#                        defaul is 32,32,128,128
#
# Use -ac option if you have problems with access control.

# Get current cookie produced by desktop manager.

COOKIE=`xauth list |grep ${HOSTNAME}/unix:0 | grep MIT | cut -f 5 -d ' '`

echo -ne "\nCookie for session is ${COOKIE}\n"
echo -ne "If you are running your clients as another user\n"
echo -ne "enable access to this session by running something like \n"
echo -ne "xauth add ${HOSTNAME}/unix${NX_AGENT} MIT-MAGIC-COOKIE-1 ${COOKIE}\n"
echo -ne "and be sure you provide the right display number\n"

# Let agent pass the right cookie to real X server.

xauth add ${HOSTNAME}/unix:${NX_PORT} MIT-MAGIC-COOKIE-1 ${COOKIE}
xauth add ${HOSTNAME}:${NX_PORT} MIT-MAGIC-COOKIE-1 ${COOKIE}

#
# Agent.
#
#nx-X11/programs/Xserver/nxagent -fp unix/:7100 -display ${NX_DISPLAY} -class TrueColor -noreset -geometry 720x540+0+0 -auth ${HOME}/.Xauthority -name 'NX' ${NX_AGENT} 2>>${NX_ROOT}/C${NX_PORT}/session &

#
# VNC Viewer.
#
#nxviewer/nxviewer/nxviewer -passwd ~/.vnc/passwd -display ${NX_DISPLAY} :1 2>>${NX_ROOT}/C${NX_PORT}/session &

#
# Mozilla.
#
export DISPLAY=${NX_DISPLAY}
mozilla 2>>${NX_ROOT}/C${NX_PORT}/session &

#
# Konqueror.
#
#export DISPLAY=${NX_DISPLAY}
#konqueror 2>>${NX_ROOT}/C${NX_PORT}/session &

# Let clients connect to the agent.

xauth add ${HOSTNAME}/unix${NX_AGENT} MIT-MAGIC-COOKIE-1 ${COOKIE}
xauth add ${HOSTNAME}${NX_AGENT} MIT-MAGIC-COOKIE-1 ${COOKIE}

#DISPLAY=${NX_AGENT} ; startkde
#DISPLAY=${NX_AGENT} ; gnome-session

echo ""
