#!/bin/sh

#/**************************************************************************/
#/*                                                                        */
#/* Copyright (c) 2001, 2011 NoMachine, http://www.nomachine.com/.         */
#/*                                                                        */
#/* NXSCRIPTS, NX protocol compression and NX extensions to this software  */
#/* are copyright of NoMachine. Redistribution and use of the present      */
#/* software is allowed according to terms specified in the file LICENSE   */
#/* which comes in the source distribution.                                */
#/*                                                                        */
#/* Check http://www.nomachine.com/licensing.html for applicability.       */
#/*                                                                        */
#/* NX and NoMachine are trademarks of Medialogic S.p.A.                   */
#/*                                                                        */
#/* All rights reserved.                                                   */
#/*                                                                        */
#/**************************************************************************/


#
# Plase note that nx-X11 constitutes an exception.
# Because of size of the whole package, updates
# are delivered separately.
#

set -x

if [ `uname` = "SunOS" ] ; then
  TAR=gtar
else
  TAR=tar
fi


#
# Make a tar with all updated files
# pertaining to nx-X11-org.
#

$TAR zcvf nx-X11-org-XXX-updated.tar.gz `find nx-X11-org -name \*.NX.updated`

